export const degreeOptionsKey = "DEGREE_OPTIONS"
export const personalInfoKey = "PERSONAL_FORMIK_VALUES"
export const experienceKey = "EXPERIENCE_FORMIK_VALUES"
export const educationKey = "EDUCATION_FORMIK_VALUES"
export const submittedPersonalInfoKey = "SUBMITTED_PERSONAL_INFO"
export const submittedExperienceKey = "SUBMITTED_EXPERIENCE"
export const submittedEducationKey = "SUBMITTED_EDUCATION"
export const resivedResumeKey = "RESIVED_RESUME"